### ISSUE TITLE
Hi, I've installed your custom repository and it shows up in HACS but when I got to integrations it doesn't show. Restarted HA multiple times now.

### ISSUE THREAD

**Issue by Zetto12** [mjoshd/hyperhdr-ha#1]
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by mjoshd** [comment]
After adding the custom repository to HACS, clicking the Download button for the HyperHDR custom component, and restarting Home Assistant there is still a little more to do.

You still have to go to the integrations page then click the new "Add integration" button in the lower-right corner (new as of 2021.12.0) then search for HyperHDR in the list.

![image](https://user-images.githubusercontent.com/35782597/147579124-8e5b006a-45d4-4f25-b1b0-cf18abfa542e.png)

**Comment by undulattice** [comment]
I'm having the same problem.
Installed in HACS, but it doesn't appear in the list of available integrations.

<img width="538" alt="Screenshot 2021-12-29 at 11 39 26" src="https://user-images.githubusercontent.com/63560223/147658607-880cc432-ae9c-4b8e-a735-922a6996b0cd.png">

<img width="545" alt="Screenshot 2021-12-29 at 11 39 44" src="https://user-images.githubusercontent.com/63560223/147658620-915a8d86-e7bf-48ba-8566-18218ea741d7.png">

**Comment by undulattice** [comment]
> I'm having the same problem. Installed in HACS, but it doesn't appear in the list of available integrations.

Scratch that.
Has appeared now. Seems like it just took some time after the reboot. :-)

**Comment by mjoshd** [comment]
Excellent! Sounds like you got it solved.

**Comment by bfbones** [comment]
I need to reopen this: got the same Problem.
Using HA 2022.2.5 and 0.0.5 of your integration. Same results, HyperHDR isn't in the list.
Also not after trying 0.0.4, 0.0.2 nor restarting HA multiple times or simply waiting for hours.

Something's still wrong with that config routine :(

Can you have a look?

I checked the looks, there's nothing obvious, only that I have the custom component installed.

Is there a way to configure it manually?
