### ISSUE TITLE
The HyperHDR Ambilight instance did not report its id

### ISSUE THREAD

**Issue by Jenematalia** [mjoshd/hyperhdr-ha#10]
Not really able to provide any logs since it won't integrate with Home Assistant but am running v0.0.5. Verified correct installation through HACS and am able to add this to my integrations via the add integrations page of HA. However upon putting in the IP (which I also verified is correct), it gives 'The HyperHDR Ambilight instance did not report its id' abort error. Have also verified the JSON Server port is the default 19444

**Comment by Jenematalia** [comment]
Not really sure what else to troubleshoot here at this point.

**Comment by Jenematalia** [comment]
I've also tried adding an API token but that doesn't seem to help the issue; have since removed a user made token that I used and the automatically created new one through add integration prompt

**Comment by mjoshd** [comment]
I have tried repeatedly (using both RPi & PC installations) but I cannot reproduce the issue you are describing. Every time I try to set up the integration it works as intended.

Are you using current stable versions: `HyperHDR 17.x` and `Home Assistant 2022.3.x` and do you have `default_config:` enabled in your Home Assistant `configuration.yaml`?

If not then I recommend migrating/updating/enabling as needed, rebooting everything, then trying to set up the integration again.

If you are already using those versions and have 'default_config:' enabled, the only other thing I can think of for you to try is to make a backup of your HyperHDR configuration then wipe/reflash/reinstall and try setting up the integration with a completely fresh HyperHDR installation. 

If you still have trouble with a fresh installation then something on your network must be blocking the communication.

**Comment by Jenematalia** [comment]
I am running the latest of HA but not HyperHDR, I'm running 16.0.0.0

**Comment by Jenematalia** [comment]
I didn't think that would be a breaking issue though. I'll update it when I get a chance today

**Comment by Jenematalia** [comment]
Haven't gotten around to upgrade my HyperHDR but I did find it's ID via trying to set up the old Hyperion integration. Is there any way to manually add it to the HyperHDR integration?

**Comment by mjoshd** [comment]
No and I don't recommend trying. 

A decent amount of things changed from v16 to v17 (API calls, etc) so even if you were somehow able to hack it in there would be multiple things that just don't work right.

If you want compatability with this integration then I recommend upgrading your HyperHDR installation to the current stable release (v17 at the time of this writing).

**Comment by mjoshd** [comment]
Two weeks with no reply. Closing.

**Comment by j26w** [comment]
I'm having this same issue. Any resolution?

Version 19.0.0.0. Home Assistant 2023.3.3, Supervisor 2023.03.1

**Comment by NefariusDeus** [comment]
Damn i have the exact same problem... Using HyperHDR 20.0.0.0

**Comment by harphere** [comment]
I'm having the same issue with HyperHdr - 22.0.0beta2 and Home Assistant Container Core 2026.7.2.
