### ISSUE TITLE
Cannot find HyperHDR in the Integrations on core-2022.5.2

### ISSUE THREAD

**Issue by smithsalvi** [mjoshd/hyperhdr-ha#12]
I have added the URL to the Custom Repositories and rebooted Home Assistant running on my R Pi 4.

However, when I go to Settings -> Devices & Services -> Add Integration button and search for HyperHDR I can not find it.

Is this because of the new version 2022.5.2 ???

I am new to Home Assistant please advise.

**Comment by mjoshd** [comment]
Hi smithsalvi. 

Home Assistant 2022.5.2 is not required but updating to the current version is always a good first step for troubleshooting. If you have not yet updated then I would recommend doing so. 

I see you mentioned added the custom repository but did not see any mention of downloading & installation after adding the repository.

1. Please check in your `HACS > Integrations` screen (down near the bottom) and verify if the custom component is downloaded & installed. If it is not installed, please use the '+ Explore & Download Repositories' button to do so, then restart Home Assistant.
![image](https://user-images.githubusercontent.com/35782597/167290330-fcf8a307-b1d0-4cd1-8e46-c39a2343946a.png)

1. If it is installed, and you have rebooted after the installation, then please check to see if HACS actually placed the files where they need to be. This would in the `config\custom_components` directory of your Home Assistant installation.
![image](https://user-images.githubusercontent.com/35782597/167290691-a7d08a95-cd66-4795-a9c0-9ead23031669.png)

1. If the files are where they are supposed to be then the only other thing I can think of is that something may be blocking your Home Assistant from getting the required python repo, that could potentially prevent it from showing up and/or working correctly.

1. Make sure there is nothing on your network that is blocking/filtering Home Assistant such as PiHole, AdGuard, PFSense, etc. and consider adjusting your Home Assistant DNS settings to have multiple addresses; I use 3 in the DNS Servers field `1.1.1.1, 9.9.9.9, 8.8.8.8` for resiliency.

1. If all else fails, please set up test environment with a completely fresh Home Assistant installation (100% stock/default settings, do not restore a backup) using a separate micro-SD card, Virtual Machine, or old computer/laptop then download and extract this repo and copy just the hyperhdr directory inside of custom_components then reboot and check to see if it appears in the integrations list.


If you followed all of the above suggestions but need further assistantce then please provide plenty of details about the outcome of each one of the numbered suggestions listed above.

**Comment by mjoshd** [comment]
I have just now added some additional wording regarding installation, both via HACS & manually; hopefully that helps to clarify the required steps.

**Comment by mjoshd** [comment]
Two weeks with no reply. Closing.
