### ISSUE TITLE
Brightness slider not working

### ISSUE THREAD

**Issue by lightdsn** [mjoshd/hyperhdr-ha#17]
Hi, I have 3 instances of Hyper HDR running in my setup and they work great other than the brightness slider in home assistant doesn't work. It seems like it's deactivated. It has no effect if it's set to USB capture or one of the effects. Is anyone else experiencing this? Thank you!

**Comment by mjoshd** [comment]
Did you follow the post setup steps on the wiki?

https://github.com/mjoshd/hyperhdr-ha/wiki#post-setup-advice

Let me know if that helps.

**Comment by lightdsn** [comment]
That did it, thank you, wasn’t mentioned in this tutorial I followed previously. Thanks for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
