### ISSUE TITLE
Closing this PR as I've just created my own fork of hyperion-py and hyperion-ha that don't rename every constant/variable to "HyperHDR" from "hyperion" as that makes tracking the diffs from the official component way harder. My fork of the official hyperion-ng component synthesizes stuff from this fork as well as hyperhdr-py. It lives at https://github.com/andrew-kennedy/hyperhdr-ha

### ISSUE THREAD

**Issue by mhoogenbosch** [mjoshd/hyperhdr-ha#23]
Closing this PR as I've just created my own fork of hyperion-py and hyperion-ha that don't rename every constant/variable to "HyperHDR" from "hyperion" as that makes tracking the diffs from the official component way harder. My fork of the official hyperion-ng component synthesizes stuff from this fork as well as hyperhdr-py. It lives at https://github.com/andrew-kennedy/hyperhdr-ha

I'm still having the "none" names issue in entities but it seems to be working.

_Originally posted by @andrew-kennedy in https://github.com/mjoshd/hyperhdr-ha/issues/21#issuecomment-2036677551_

**Comment by mhoogenbosch** [comment]
I just updated to the https://github.com/andrew-kennedy/hyperhdr-ha release. There is no communication between HA and HyperHDR.

I can't select USB Capture from within HA.

**Comment by andrew-kennedy** [comment]
Hmm I'm still working on my own fork but yeah I'm having bugs too with it and the "none" names issue. I'm hewing as close to the official hyperion integration but still investigating where the differences lie.

**Comment by mjoshd** [comment]
Issue not related to this repo.
Closed.
