### ISSUE TITLE
Update to V.20.0.0

### ISSUE THREAD

**Issue by grssll** [mjoshd/hyperhdr-ha#24]
Is it possible to to update to V.20.0.0?
Thanks

**Comment by papapep514** [comment]
I would second that a well. is an update possible?

**Comment by Mofx-01** [comment]
Can you please update to v20?

**Comment by mjoshd** [comment]
![image](https://github.com/user-attachments/assets/675d0876-123e-4290-8b4b-e5347f784c36)

HyperHDR v20.0.0.0 works perfectly fine. 
Closing.

**Comment by Mofx-01** [comment]
Can you explain how do i update to v20? Im new to this. Thanks

**Comment by mjoshd** [comment]
This custom component and HyperHDR are two separate things

This custom component is on version 0.0.7

The version 20.0.0.0 update/installation needs to be applied to the HyperHDR instance (which runs on Windows, Linux/Raspberry Pi, Mac) and awawa-dev's provided instructions are performed on the Operating System where the HyperHDR instance is running.

**Comment by Mofx-01** [comment]
I see! Thanks you for the clarification. Have a nice day!
