### ISSUE TITLE
Camera Stream

### ISSUE THREAD

**Issue by leoravagnani** [mjoshd/hyperhdr-ha#25]
I was playing around with Hyperion before trying HyperHDR, it seems so much better. The official Hyperion integration provides a camera entity with the stream.

From what I gathered from #3, the feature was removed because it was not working correctly. Any chance of getting it back?

More people are asking for something similar on https://github.com/awawa-dev/HyperHDR/discussions/475.

Maybe a link from the API side is enough for people to set their own camera entities (enabling this to be properly solved via the integration as well).

**Comment by CZonin** [comment]
Would love this as well. I really liked having it when using Hyperion.

**Comment by mjoshd** [comment]
The camera is disabled because it does not work and I am unable to fix it.

Please feel free to fix the issue and create a pull request.
