### ISSUE TITLE
Failed to determine if authorization is required

### ISSUE THREAD

**Issue by jonskoglund** [mjoshd/hyperhdr-ha#5]
## Version of the custom_component
V0.0.4

## Describe the bug
When setting up the integration the component asks for host and port. This is what I used:
host: 192.168.1.155
port: 8090
Then I got the error message:
Aborted. Failed to determine if authorization is required.

## Debug log
Sorry. Can't provide detailed logs. I tried setting it up but I couldn't make it work. Any tips or code to do this are very welcome.

**Comment by mjoshd** [comment]
Port 8090 is used for accessing the web UI of HyperHDR with a web browser, not for connecting the integration.

When you begin to set up the integration it should pre-fill the port field with `19444`, which is what it should be for 99% of installations (the only time it would be different is if you have customized the JSON Server port in HyperHDR settings).
![image](https://user-images.githubusercontent.com/35782597/152517755-e3152015-88dc-4989-a58c-80420de8eb0c.png)

Please try setting the integration up again but this time do not change the pre-filled port number, just enter the ip address of your HyperHDR instance. In your case this would be `192.168.1.155`

Hopefully this helps.

**Comment by jonskoglund** [comment]
Yes worked like a charm. Somehow I didn't try the most obvious solution. There still are some other issues with brightness and turning the light on or off in a lovelace card.

**Comment by mjoshd** [comment]
The best settings for an individual's HyperHDR setup are subjective and will vary greatly but my recommendations are 
- go into the HyperHDR web UI >> Image Processing >> Color Calibration 
  - un-check `Classic HyperHDR calibration`
  - un-check `Colored backlight`
  - click `Save settings`
 
The page/settings should be at `http://IPADDRESS:8090/#processing` just replace `IPADDRESS` with the ip of your HyperHDR instance.
